//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int RoomId { get; set; }
        public int HotelId { get; set; }
        public string RoomName { get; set; }
        public int RoomCategory { get; set; }
        public string RoomPrice { get; set; }
        public string IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Hotel Hotel { get; set; }

        public virtual Booking Booking { get; set; }
        public virtual RoomCategory RoomCategory1 { get; set; }

        
    }
    public class getrooms
    {
        public string RoomName { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public string RoomCategoryName { get; set; }
        public string RoomPrice { get; set; }
    }
}
