//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Product
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Select Category")]
        public Nullable<int> CategoryId { get; set; }

        [DisplayName("Product Name")]
        [Required(ErrorMessage = "Product Name required")]
        [StringLength(50, MinimumLength = 3)]
        public string ProductName { get; set; }

        [DisplayName("Price")]
        [Required(ErrorMessage = "Mention Price")]
        [Range(typeof(Decimal), "0", "999", ErrorMessage = "{0} must be a decimal/number between {1} and {2}.")]
        public string Price { get; set; }

        [DisplayName("Description")]
        [Required(ErrorMessage = "Description required")]
        public string Description { get; set; }

        [DisplayName("Product Image")]
        public string ImagePath { get; set; }

        [DisplayName("Large Description")]
        [Required(ErrorMessage = " Large Description required")]
        public string LDescription { get; set; }

        [DisplayName("Large Product Image")]
        public string LImagePath { get; set; }

        [DisplayName("Quantity")]
        [Required(ErrorMessage = "Mention Quantity")]
        [Range(typeof(Decimal), "0", "999999", ErrorMessage = "{0} must be a decimal/number between {1} and {2}.")]

        public string Quantity { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
        public HttpPostedFileBase LImageFile { get; set; }

        public virtual Category Category { get; set; }
    }
}
